"""preza_gen.ingest — pull external source material into data/ + write a provenance manifest.

The FIRST caller of utils.hardlink_or_copy: local files are hardlinked (byte-identical, zero
copy) into data/source[/drafts]; URLs (e.g. Google Slides `.../export/pptx`) are downloaded.
Writes settings/files.yml (source/method/inode/bytes) so provenance is GENERATED, not hand-kept.
NotebookLM has no public API — export manually into data/source/drafts/ and register a `src:` line.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import click

from .utils import expand_path, hardlink_or_copy, load_yaml, log

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_CONFIG = _REPO_ROOT / "settings" / "config.yml"


@dataclass
class Ingested:
    """One manifest entry: what landed where, how, and its change-detection cursor."""

    dst: str  # repo-relative destination
    source: str  # tilde-collapsed local path, or url
    method: str  # hardlink | copy | download
    inode: int
    bytes: int


def _collapse_home(p: str) -> str:
    """Collapse an absolute path under $HOME back to '~/…' for portable manifests.

    >>> _collapse_home("/nonexistent/x")
    '/nonexistent/x'
    """
    home = str(Path.home())
    return "~" + p[len(home) :] if p.startswith(home) else p


def _fetch_url(url: str, dst: Path) -> None:
    try:
        import requests  # optional dep: '.[orchestration]' (lazy — only URL targets need it)
    except ModuleNotFoundError as e:  # pragma: no cover
        raise ModuleNotFoundError(
            "downloading URL targets needs `requests` — `uv sync --extra orchestration`"
        ) from e
    dst.parent.mkdir(parents=True, exist_ok=True)
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    dst.write_bytes(r.content)


def ingest_target(t: dict, repo_root: Path) -> Ingested:
    """Ingest one {src|url, dst} target into data/; return its manifest entry. Fail-loud."""
    dst_rel = t["dst"]
    dst = repo_root / dst_rel
    if "src" in t:
        src = expand_path(t["src"])
        if not src.is_file():
            raise FileNotFoundError(f"ingest src missing: {src}")
        method = hardlink_or_copy(src, dst)
        source = _collapse_home(str(src))
    elif "url" in t:
        _fetch_url(t["url"], dst)
        method, source = "download", t["url"]
    else:
        raise ValueError(f"ingest target needs 'src' or 'url': {t}")
    st = dst.stat()
    log.success(f"{method:>8}  {dst_rel}  ({st.st_size} B)")
    return Ingested(dst=dst_rel, source=source, method=method, inode=st.st_ino, bytes=st.st_size)


def write_manifest(entries: list[Ingested], manifest: Path) -> None:
    """Serialize entries → files.yml (source/method/inode/bytes, insertion order)."""
    import yaml

    doc = {
        e.dst: {"source": e.source, "method": e.method, "inode": e.inode, "bytes": e.bytes}
        for e in entries
    }
    manifest.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# files.yml — provenance of external inputs ingested into data/\n"
        "# (generated by preza_gen.ingest — do not hand-edit).\n"
        "# method: hardlink (same inode) | copy (cross-volume fallback) | download (url).\n"
    )
    body = yaml.safe_dump({"ingested": doc}, allow_unicode=True, sort_keys=False)
    manifest.write_text(header + body, encoding="utf-8")
    log.success(f"manifest → {manifest}  ({len(entries)} entries)")


def ingest(config_path: str | Path) -> list[Ingested]:
    """Run every `ingest.targets` entry from the project config, then write the manifest."""
    section = load_yaml(config_path)["ingest"]
    repo_root = expand_path(config_path).resolve().parents[1]  # settings/config.yml → repo root
    entries = [ingest_target(t, repo_root) for t in section["targets"]]
    write_manifest(entries, repo_root / section["manifest"])
    return entries


@click.command()
@click.option(
    "--config",
    "config_path",
    default=str(_DEFAULT_CONFIG),
    show_default=True,
    help="project config yaml with an `ingest:` section",
)
def main(config_path: str) -> None:
    ingest(config_path)


if __name__ == "__main__":
    main()
